main[2015-08-16 21:11:12463] || INFO || ClassPathXmlApplicationContext || Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@48f0c0d3: startup date [Sun Aug 16 21:11:12 CST 2015]; root of context hierarchy
main[2015-08-16 21:11:12611] || INFO || XmlBeanDefinitionReader || Loading XML bean definitions from class path resource [applicationContext.xml]
main[2015-08-16 21:11:13234] || INFO || PropertyPlaceholderConfigurer || Loading properties file from class path resource [jdbc.properties]
main[2015-08-16 21:11:13297] || INFO || DefaultListableBeanFactory || Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@112c3327: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0,dataSource,sessionFactory,logonDao,logonService,freemarkerManager,org.springframework.aop.config.internalAutoProxyCreator,org.springframework.aop.aspectj.AspectJPointcutAdvisor#0,org.springframework.aop.aspectj.AspectJPointcutAdvisor#1,org.springframework.aop.aspectj.AspectJPointcutAdvisor#2,aopRiZhi,myRiZhi,logonAction,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
main[2015-08-16 21:11:13655] || INFO || MLog || MLog clients using log4j logging.
main[2015-08-16 21:11:14197] || INFO || C3P0Registry || Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? true; trace: 10]
main[2015-08-16 21:11:14727] || INFO || Version || Hibernate Commons Annotations 3.2.0.Final
main[2015-08-16 21:11:14734] || INFO || Environment || Hibernate 3.6.10.Final
main[2015-08-16 21:11:14736] || INFO || Environment || hibernate.properties not found
main[2015-08-16 21:11:14739] || INFO || Environment || Bytecode provider name : javassist
main[2015-08-16 21:11:14743] || INFO || Environment || using JDK 1.4 java.sql.Timestamp handling
main[2015-08-16 21:11:14874] || INFO || AnnotationBinder || Binding entity from annotated class: org.veight.admin.domain.Admin
main[2015-08-16 21:11:14901] || INFO || EntityBinder || Bind entity org.veight.admin.domain.Admin on table Admin
main[2015-08-16 21:11:14948] || INFO || Configuration || Hibernate Validator not found: ignoring
main[2015-08-16 21:11:14951] || INFO || AnnotationSessionFactoryBean || Building new Hibernate SessionFactory
main[2015-08-16 21:11:14954] || INFO || HibernateSearchEventListenerRegister || Unable to find org.hibernate.search.event.FullTextIndexEventListener on the classpath. Hibernate Search is not enabled.
main[2015-08-16 21:11:14958] || INFO || ConnectionProviderFactory || Initializing connection provider: org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider
main[2015-08-16 21:11:155] || INFO || AbstractPoolBackedDataSource || Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> 1hge15x9bf5qjvwul7ywb|750e687b, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1hge15x9bf5qjvwul7ywb|750e687b, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2[2015-08-16 21:11:44245] || WARN || BasicResourcePool || com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@4cd1ad08 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1127)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:356)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2502)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
	at java.net.Socket.connect(Socket.java:527)
	at java.net.Socket.connect(Socket.java:476)
	at java.net.Socket.<init>(Socket.java:373)
	at java.net.Socket.<init>(Socket.java:216)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:306)
	... 19 more
com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1[2015-08-16 21:11:44251] || WARN || BasicResourcePool || com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@436d4b50 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1127)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:356)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2502)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
	at java.net.Socket.connect(Socket.java:527)
	at java.net.Socket.connect(Socket.java:476)
	at java.net.Socket.<init>(Socket.java:373)
	at java.net.Socket.<init>(Socket.java:216)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:306)
	... 19 more
com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0[2015-08-16 21:11:44252] || WARN || BasicResourcePool || com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@1f61509b -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1127)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:356)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2502)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
	at java.net.Socket.connect(Socket.java:527)
	at java.net.Socket.connect(Socket.java:476)
	at java.net.Socket.<init>(Socket.java:373)
	at java.net.Socket.<init>(Socket.java:216)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:306)
	... 19 more
main[2015-08-16 21:11:44253] || WARN || JDBCExceptionReporter || SQL Error: 0, SQLState: null
main[2015-08-16 21:11:44254] || ERROR || JDBCExceptionReporter || Connections could not be acquired from the underlying database!
main[2015-08-16 21:11:44254] || WARN || SettingsFactory || Could not obtain connection to query metadata
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:83)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:113)
	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2863)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2859)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1870)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:863)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:782)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:589)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.veight.logon.action.TestAopLog4j.main(TestAopLog4j.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 28 more
main[2015-08-16 21:11:44279] || INFO || Dialect || Using dialect: org.hibernate.dialect.MySQLDialect
main[2015-08-16 21:11:44290] || INFO || JdbcSupportLoader || Disabling contextual LOB creation as connection was null
main[2015-08-16 21:11:44291] || INFO || TransactionFactoryFactory || Transaction strategy: org.springframework.orm.hibernate3.SpringTransactionFactory
main[2015-08-16 21:11:44292] || INFO || TransactionManagerLookupFactory || No TransactionManagerLookup configured (in JTA environment, use of read-write or transactional second-level cache is not recommended)
main[2015-08-16 21:11:44292] || INFO || SettingsFactory || Automatic flush during beforeCompletion(): disabled
main[2015-08-16 21:11:44292] || INFO || SettingsFactory || Automatic session close at end of transaction: disabled
main[2015-08-16 21:11:44293] || INFO || SettingsFactory || Scrollable result sets: disabled
main[2015-08-16 21:11:44293] || INFO || SettingsFactory || JDBC3 getGeneratedKeys(): disabled
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || JDBC result set fetch size: 50
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || Connection release mode: auto
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || Maximum outer join fetch depth: 2
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || Default batch fetch size: 1
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || Generate SQL with comments: disabled
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || Order SQL updates by primary key: disabled
main[2015-08-16 21:11:44294] || INFO || SettingsFactory || Order SQL inserts for batching: disabled
main[2015-08-16 21:11:44295] || INFO || SettingsFactory || Query translator: org.hibernate.hql.ast.ASTQueryTranslatorFactory
main[2015-08-16 21:11:44296] || INFO || ASTQueryTranslatorFactory || Using ASTQueryTranslatorFactory
main[2015-08-16 21:11:44296] || INFO || SettingsFactory || Query language substitutions: {}
main[2015-08-16 21:11:44296] || INFO || SettingsFactory || JPA-QL strict compliance: disabled
main[2015-08-16 21:11:44296] || INFO || SettingsFactory || Second-level cache: disabled
main[2015-08-16 21:11:44296] || INFO || SettingsFactory || Query cache: disabled
main[2015-08-16 21:11:44296] || INFO || SettingsFactory || Cache region factory : org.hibernate.cache.impl.NoCachingRegionFactory
main[2015-08-16 21:11:44297] || INFO || SettingsFactory || Optimize cache for minimal puts: disabled
main[2015-08-16 21:11:44298] || INFO || SettingsFactory || Structured second-level cache entries: disabled
main[2015-08-16 21:11:44301] || INFO || SettingsFactory || Statistics: disabled
main[2015-08-16 21:11:44301] || INFO || SettingsFactory || Deleted entity synthetic identifier rollback: disabled
main[2015-08-16 21:11:44301] || INFO || SettingsFactory || Default entity-mode: pojo
main[2015-08-16 21:11:44301] || INFO || SettingsFactory || Named query checking : enabled
main[2015-08-16 21:11:44301] || INFO || SettingsFactory || Check Nullability in Core (should be disabled when Bean Validation is on): enabled
main[2015-08-16 21:11:44316] || INFO || SessionFactoryImpl || building session factory
main[2015-08-16 21:11:44323] || INFO || BasicTypeRegistry || Type registration [materialized_clob] overrides previous : org.hibernate.type.MaterializedClobType@7593c366
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [wrapper_materialized_blob] overrides previous : org.hibernate.type.WrappedMaterializedBlobType@380199d8
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [blob] overrides previous : org.hibernate.type.BlobType@711b50a1
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [java.sql.Blob] overrides previous : org.hibernate.type.BlobType@711b50a1
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [clob] overrides previous : org.hibernate.type.ClobType@384ab40a
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [java.sql.Clob] overrides previous : org.hibernate.type.ClobType@384ab40a
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [characters_clob] overrides previous : org.hibernate.type.PrimitiveCharacterArrayClobType@30721965
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [materialized_blob] overrides previous : org.hibernate.type.MaterializedBlobType@12e14ebc
main[2015-08-16 21:11:44324] || INFO || BasicTypeRegistry || Type registration [wrapper_characters_clob] overrides previous : org.hibernate.type.CharacterArrayClobType@5f82253
main[2015-08-16 21:11:44338] || WARN || UUIDHexGenerator || Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
main[2015-08-16 21:11:44515] || INFO || SessionFactoryObjectFactory || Not binding factory to JNDI, no JNDI name configured
main[2015-08-16 21:11:44522] || INFO || SchemaUpdate || Running hbm2ddl schema update
main[2015-08-16 21:11:44522] || INFO || SchemaUpdate || fetching database metadata
com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0[2015-08-16 21:12:13606] || WARN || BasicResourcePool || com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@226e8504 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1127)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:356)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2502)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
	at java.net.Socket.connect(Socket.java:527)
	at java.net.Socket.connect(Socket.java:476)
	at java.net.Socket.<init>(Socket.java:373)
	at java.net.Socket.<init>(Socket.java:216)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:306)
	... 19 more
com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2[2015-08-16 21:12:13606] || WARN || BasicResourcePool || com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@5dedb45 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1127)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:356)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2502)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
	at java.net.Socket.connect(Socket.java:527)
	at java.net.Socket.connect(Socket.java:476)
	at java.net.Socket.<init>(Socket.java:373)
	at java.net.Socket.<init>(Socket.java:216)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:306)
	... 19 more
main[2015-08-16 21:12:13607] || WARN || JDBCExceptionReporter || SQL Error: 0, SQLState: null
main[2015-08-16 21:12:13608] || ERROR || JDBCExceptionReporter || Connections could not be acquired from the underlying database!
main[2015-08-16 21:12:13608] || ERROR || SchemaUpdate || could not get database metadata
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:83)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:168)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:375)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1872)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:863)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:782)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:589)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.veight.logon.action.TestAopLog4j.main(TestAopLog4j.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 28 more
main[2015-08-16 21:12:13609] || ERROR || SchemaUpdate || could not complete schema update
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:83)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:168)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:375)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1872)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:863)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:782)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:589)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.veight.logon.action.TestAopLog4j.main(TestAopLog4j.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 28 more
main[2015-08-16 21:13:25775] || INFO || ClassPathXmlApplicationContext || Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@50c931fc: startup date [Sun Aug 16 21:13:25 CST 2015]; root of context hierarchy
main[2015-08-16 21:13:25829] || INFO || XmlBeanDefinitionReader || Loading XML bean definitions from class path resource [applicationContext.xml]
main[2015-08-16 21:13:26381] || INFO || PropertyPlaceholderConfigurer || Loading properties file from class path resource [jdbc.properties]
main[2015-08-16 21:13:26421] || INFO || DefaultListableBeanFactory || Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@48fd918a: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0,dataSource,sessionFactory,logonDao,logonService,freemarkerManager,org.springframework.aop.config.internalAutoProxyCreator,org.springframework.aop.aspectj.AspectJPointcutAdvisor#0,org.springframework.aop.aspectj.AspectJPointcutAdvisor#1,org.springframework.aop.aspectj.AspectJPointcutAdvisor#2,aopRiZhi,myRiZhi,logonAction,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
main[2015-08-16 21:13:26634] || INFO || MLog || MLog clients using log4j logging.
main[2015-08-16 21:13:26976] || INFO || C3P0Registry || Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? true; trace: 10]
main[2015-08-16 21:13:27369] || INFO || Version || Hibernate Commons Annotations 3.2.0.Final
main[2015-08-16 21:13:27375] || INFO || Environment || Hibernate 3.6.10.Final
main[2015-08-16 21:13:27376] || INFO || Environment || hibernate.properties not found
main[2015-08-16 21:13:27379] || INFO || Environment || Bytecode provider name : javassist
main[2015-08-16 21:13:27383] || INFO || Environment || using JDK 1.4 java.sql.Timestamp handling
main[2015-08-16 21:13:27497] || INFO || AnnotationBinder || Binding entity from annotated class: org.veight.admin.domain.Admin
main[2015-08-16 21:13:27521] || INFO || EntityBinder || Bind entity org.veight.admin.domain.Admin on table Admin
main[2015-08-16 21:13:27560] || INFO || Configuration || Hibernate Validator not found: ignoring
main[2015-08-16 21:13:27561] || INFO || AnnotationSessionFactoryBean || Building new Hibernate SessionFactory
main[2015-08-16 21:13:27564] || INFO || HibernateSearchEventListenerRegister || Unable to find org.hibernate.search.event.FullTextIndexEventListener on the classpath. Hibernate Search is not enabled.
main[2015-08-16 21:13:27567] || INFO || ConnectionProviderFactory || Initializing connection provider: org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider
main[2015-08-16 21:13:27605] || INFO || AbstractPoolBackedDataSource || Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> 1hge15x9bf5tehr1zmm72|67148603, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1hge15x9bf5tehr1zmm72|67148603, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
main[2015-08-16 21:13:27834] || INFO || Dialect || Using dialect: org.hibernate.dialect.MySQLDialect
main[2015-08-16 21:13:27842] || INFO || JdbcSupportLoader || Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
main[2015-08-16 21:13:27842] || INFO || SettingsFactory || Database ->
       name : MySQL
    version : 5.6.23
      major : 5
      minor : 6
main[2015-08-16 21:13:27843] || INFO || SettingsFactory || Driver ->
       name : MySQL Connector Java
    version : mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c )
      major : 5
      minor : 1
main[2015-08-16 21:13:27848] || INFO || TransactionFactoryFactory || Transaction strategy: org.springframework.orm.hibernate3.SpringTransactionFactory
main[2015-08-16 21:13:27849] || INFO || TransactionManagerLookupFactory || No TransactionManagerLookup configured (in JTA environment, use of read-write or transactional second-level cache is not recommended)
main[2015-08-16 21:13:27849] || INFO || SettingsFactory || Automatic flush during beforeCompletion(): disabled
main[2015-08-16 21:13:27849] || INFO || SettingsFactory || Automatic session close at end of transaction: disabled
main[2015-08-16 21:13:27850] || INFO || SettingsFactory || JDBC batch size: 30
main[2015-08-16 21:13:27850] || INFO || SettingsFactory || JDBC batch updates for versioned data: disabled
main[2015-08-16 21:13:27850] || INFO || SettingsFactory || Scrollable result sets: enabled
main[2015-08-16 21:13:27850] || INFO || SettingsFactory || JDBC3 getGeneratedKeys(): enabled
main[2015-08-16 21:13:27851] || INFO || SettingsFactory || JDBC result set fetch size: 50
main[2015-08-16 21:13:27851] || INFO || SettingsFactory || Connection release mode: auto
main[2015-08-16 21:13:27851] || INFO || SettingsFactory || Maximum outer join fetch depth: 2
main[2015-08-16 21:13:27851] || INFO || SettingsFactory || Default batch fetch size: 1
main[2015-08-16 21:13:27851] || INFO || SettingsFactory || Generate SQL with comments: disabled
main[2015-08-16 21:13:27851] || INFO || SettingsFactory || Order SQL updates by primary key: disabled
main[2015-08-16 21:13:27852] || INFO || SettingsFactory || Order SQL inserts for batching: disabled
main[2015-08-16 21:13:27852] || INFO || SettingsFactory || Query translator: org.hibernate.hql.ast.ASTQueryTranslatorFactory
main[2015-08-16 21:13:27853] || INFO || ASTQueryTranslatorFactory || Using ASTQueryTranslatorFactory
main[2015-08-16 21:13:27853] || INFO || SettingsFactory || Query language substitutions: {}
main[2015-08-16 21:13:27853] || INFO || SettingsFactory || JPA-QL strict compliance: disabled
main[2015-08-16 21:13:27853] || INFO || SettingsFactory || Second-level cache: disabled
main[2015-08-16 21:13:27853] || INFO || SettingsFactory || Query cache: disabled
main[2015-08-16 21:13:27853] || INFO || SettingsFactory || Cache region factory : org.hibernate.cache.impl.NoCachingRegionFactory
main[2015-08-16 21:13:27854] || INFO || SettingsFactory || Optimize cache for minimal puts: disabled
main[2015-08-16 21:13:27854] || INFO || SettingsFactory || Structured second-level cache entries: disabled
main[2015-08-16 21:13:27857] || INFO || SettingsFactory || Statistics: disabled
main[2015-08-16 21:13:27857] || INFO || SettingsFactory || Deleted entity synthetic identifier rollback: disabled
main[2015-08-16 21:13:27857] || INFO || SettingsFactory || Default entity-mode: pojo
main[2015-08-16 21:13:27857] || INFO || SettingsFactory || Named query checking : enabled
main[2015-08-16 21:13:27857] || INFO || SettingsFactory || Check Nullability in Core (should be disabled when Bean Validation is on): enabled
main[2015-08-16 21:13:27868] || INFO || SessionFactoryImpl || building session factory
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [clob] overrides previous : org.hibernate.type.ClobType@4e9e75f6
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [java.sql.Clob] overrides previous : org.hibernate.type.ClobType@4e9e75f6
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [materialized_clob] overrides previous : org.hibernate.type.MaterializedClobType@55291cd
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [materialized_blob] overrides previous : org.hibernate.type.MaterializedBlobType@6fe22c75
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [wrapper_characters_clob] overrides previous : org.hibernate.type.CharacterArrayClobType@69d4eeb5
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [characters_clob] overrides previous : org.hibernate.type.PrimitiveCharacterArrayClobType@1a83e35b
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [wrapper_materialized_blob] overrides previous : org.hibernate.type.WrappedMaterializedBlobType@48c378f6
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [blob] overrides previous : org.hibernate.type.BlobType@193a83cc
main[2015-08-16 21:13:27872] || INFO || BasicTypeRegistry || Type registration [java.sql.Blob] overrides previous : org.hibernate.type.BlobType@193a83cc
main[2015-08-16 21:13:27882] || WARN || UUIDHexGenerator || Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
main[2015-08-16 21:13:27999] || INFO || SessionFactoryObjectFactory || Not binding factory to JNDI, no JNDI name configured
main[2015-08-16 21:13:283] || INFO || SchemaUpdate || Running hbm2ddl schema update
main[2015-08-16 21:13:283] || INFO || SchemaUpdate || fetching database metadata
main[2015-08-16 21:13:286] || INFO || SchemaUpdate || updating schema
main[2015-08-16 21:13:2815] || INFO || DatabaseMetadata || table not found: Admin
main[2015-08-16 21:13:2816] || INFO || DatabaseMetadata || table not found: Admin
main[2015-08-16 21:13:2839] || INFO || SchemaUpdate || schema update complete
main[2015-08-16 21:15:1094] || INFO || ClassPathXmlApplicationContext || Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@50c931fc: startup date [Sun Aug 16 21:15:10 CST 2015]; root of context hierarchy
main[2015-08-16 21:15:10146] || INFO || XmlBeanDefinitionReader || Loading XML bean definitions from class path resource [applicationContext.xml]
main[2015-08-16 21:15:10618] || INFO || PropertyPlaceholderConfigurer || Loading properties file from class path resource [jdbc.properties]
main[2015-08-16 21:15:10658] || INFO || DefaultListableBeanFactory || Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@112c3327: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0,dataSource,sessionFactory,logonDao,logonService,freemarkerManager,org.springframework.aop.config.internalAutoProxyCreator,org.springframework.aop.aspectj.AspectJPointcutAdvisor#0,org.springframework.aop.aspectj.AspectJPointcutAdvisor#1,org.springframework.aop.aspectj.AspectJPointcutAdvisor#2,aopRiZhi,myRiZhi,logonAction,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
main[2015-08-16 21:15:10851] || INFO || MLog || MLog clients using log4j logging.
main[2015-08-16 21:15:11187] || INFO || C3P0Registry || Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? true; trace: 10]
main[2015-08-16 21:15:11623] || INFO || Version || Hibernate Commons Annotations 3.2.0.Final
main[2015-08-16 21:15:11627] || INFO || Environment || Hibernate 3.6.10.Final
main[2015-08-16 21:15:11628] || INFO || Environment || hibernate.properties not found
main[2015-08-16 21:15:11632] || INFO || Environment || Bytecode provider name : javassist
main[2015-08-16 21:15:11635] || INFO || Environment || using JDK 1.4 java.sql.Timestamp handling
main[2015-08-16 21:15:11728] || INFO || AnnotationBinder || Binding entity from annotated class: org.veight.admin.domain.Admin
main[2015-08-16 21:15:11752] || INFO || EntityBinder || Bind entity org.veight.admin.domain.Admin on table Admin
main[2015-08-16 21:15:11792] || INFO || Configuration || Hibernate Validator not found: ignoring
main[2015-08-16 21:15:11794] || INFO || AnnotationSessionFactoryBean || Building new Hibernate SessionFactory
main[2015-08-16 21:15:11796] || INFO || HibernateSearchEventListenerRegister || Unable to find org.hibernate.search.event.FullTextIndexEventListener on the classpath. Hibernate Search is not enabled.
main[2015-08-16 21:15:11800] || INFO || ConnectionProviderFactory || Initializing connection provider: org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider
main[2015-08-16 21:15:11835] || INFO || AbstractPoolBackedDataSource || Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> 1hge15x9bf5vmwtrzsg8r|41759d12, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1hge15x9bf5vmwtrzsg8r|41759d12, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
main[2015-08-16 21:15:1244] || INFO || Dialect || Using dialect: org.hibernate.dialect.MySQLDialect
main[2015-08-16 21:15:1254] || INFO || JdbcSupportLoader || Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
main[2015-08-16 21:15:1254] || INFO || SettingsFactory || Database ->
       name : MySQL
    version : 5.6.23
      major : 5
      minor : 6
main[2015-08-16 21:15:1254] || INFO || SettingsFactory || Driver ->
       name : MySQL Connector Java
    version : mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c )
      major : 5
      minor : 1
main[2015-08-16 21:15:1257] || INFO || TransactionFactoryFactory || Transaction strategy: org.springframework.orm.hibernate3.SpringTransactionFactory
main[2015-08-16 21:15:1258] || INFO || TransactionManagerLookupFactory || No TransactionManagerLookup configured (in JTA environment, use of read-write or transactional second-level cache is not recommended)
main[2015-08-16 21:15:1258] || INFO || SettingsFactory || Automatic flush during beforeCompletion(): disabled
main[2015-08-16 21:15:1258] || INFO || SettingsFactory || Automatic session close at end of transaction: disabled
main[2015-08-16 21:15:1258] || INFO || SettingsFactory || JDBC batch size: 30
main[2015-08-16 21:15:1258] || INFO || SettingsFactory || JDBC batch updates for versioned data: disabled
main[2015-08-16 21:15:1259] || INFO || SettingsFactory || Scrollable result sets: enabled
main[2015-08-16 21:15:1259] || INFO || SettingsFactory || JDBC3 getGeneratedKeys(): enabled
main[2015-08-16 21:15:1259] || INFO || SettingsFactory || JDBC result set fetch size: 50
main[2015-08-16 21:15:1259] || INFO || SettingsFactory || Connection release mode: auto
main[2015-08-16 21:15:1260] || INFO || SettingsFactory || Maximum outer join fetch depth: 2
main[2015-08-16 21:15:1260] || INFO || SettingsFactory || Default batch fetch size: 1
main[2015-08-16 21:15:1260] || INFO || SettingsFactory || Generate SQL with comments: disabled
main[2015-08-16 21:15:1260] || INFO || SettingsFactory || Order SQL updates by primary key: disabled
main[2015-08-16 21:15:1260] || INFO || SettingsFactory || Order SQL inserts for batching: disabled
main[2015-08-16 21:15:1260] || INFO || SettingsFactory || Query translator: org.hibernate.hql.ast.ASTQueryTranslatorFactory
main[2015-08-16 21:15:1261] || INFO || ASTQueryTranslatorFactory || Using ASTQueryTranslatorFactory
main[2015-08-16 21:15:1261] || INFO || SettingsFactory || Query language substitutions: {}
main[2015-08-16 21:15:1261] || INFO || SettingsFactory || JPA-QL strict compliance: disabled
main[2015-08-16 21:15:1261] || INFO || SettingsFactory || Second-level cache: disabled
main[2015-08-16 21:15:1261] || INFO || SettingsFactory || Query cache: disabled
main[2015-08-16 21:15:1261] || INFO || SettingsFactory || Cache region factory : org.hibernate.cache.impl.NoCachingRegionFactory
main[2015-08-16 21:15:1262] || INFO || SettingsFactory || Optimize cache for minimal puts: disabled
main[2015-08-16 21:15:1262] || INFO || SettingsFactory || Structured second-level cache entries: disabled
main[2015-08-16 21:15:1267] || INFO || SettingsFactory || Statistics: disabled
main[2015-08-16 21:15:1268] || INFO || SettingsFactory || Deleted entity synthetic identifier rollback: disabled
main[2015-08-16 21:15:1268] || INFO || SettingsFactory || Default entity-mode: pojo
main[2015-08-16 21:15:1268] || INFO || SettingsFactory || Named query checking : enabled
main[2015-08-16 21:15:1268] || INFO || SettingsFactory || Check Nullability in Core (should be disabled when Bean Validation is on): enabled
main[2015-08-16 21:15:1282] || INFO || SessionFactoryImpl || building session factory
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [characters_clob] overrides previous : org.hibernate.type.PrimitiveCharacterArrayClobType@1bb25a82
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [clob] overrides previous : org.hibernate.type.ClobType@5a541b02
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [java.sql.Clob] overrides previous : org.hibernate.type.ClobType@5a541b02
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [wrapper_materialized_blob] overrides previous : org.hibernate.type.WrappedMaterializedBlobType@47b94ea2
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [blob] overrides previous : org.hibernate.type.BlobType@56d99277
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [java.sql.Blob] overrides previous : org.hibernate.type.BlobType@56d99277
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [materialized_blob] overrides previous : org.hibernate.type.MaterializedBlobType@661eef2c
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [materialized_clob] overrides previous : org.hibernate.type.MaterializedClobType@78e86614
main[2015-08-16 21:15:1287] || INFO || BasicTypeRegistry || Type registration [wrapper_characters_clob] overrides previous : org.hibernate.type.CharacterArrayClobType@6185e90f
main[2015-08-16 21:15:1298] || WARN || UUIDHexGenerator || Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
main[2015-08-16 21:15:12205] || INFO || SessionFactoryObjectFactory || Not binding factory to JNDI, no JNDI name configured
main[2015-08-16 21:15:12209] || INFO || SchemaUpdate || Running hbm2ddl schema update
main[2015-08-16 21:15:12209] || INFO || SchemaUpdate || fetching database metadata
main[2015-08-16 21:15:12211] || INFO || SchemaUpdate || updating schema
main[2015-08-16 21:15:12235] || INFO || TableMetadata || table found: test.Admin
main[2015-08-16 21:15:12235] || INFO || TableMetadata || columns: [id, modifydate, createdate]
main[2015-08-16 21:15:12235] || INFO || TableMetadata || foreign keys: []
main[2015-08-16 21:15:12235] || INFO || TableMetadata || indexes: [primary]
main[2015-08-16 21:15:12236] || INFO || SchemaUpdate || schema update complete
